"""
EmitFull — Mode A: render SnippetIR as a complete integration test harness.

Output: a .rs file containing #[test] functions that can be compiled with
  cargo check --tests / cargo test --no-run

The generated code:
  - Only uses the crate's public API
  - Includes necessary imports
  - Wraps each snippet in a #[test] fn
  - Inserts explicit drop() / block scope to close borrows
  - Adds #[allow(...)] attributes to suppress warnings
"""

from __future__ import annotations

from typing import Optional

from rustsynth.ir.snippet_ir import SnippetIR, Stmt, StmtKind


def render_full(
    snippet: SnippetIR,
    task_id: str,
    crate_name: Optional[str] = None,
    test_index: int = 0,
) -> str:
    """Render a SnippetIR into a complete Rust test file."""
    cn = crate_name or snippet.crate_name
    lines: list[str] = []

    lines.append(f"//! Generated by rustsynth-pcpn for task: {task_id}")
    lines.append("//! This code is compilation-valid (not semantically verified).")
    lines.append("")
    lines.append("#![allow(unused_variables)]")
    lines.append("#![allow(unused_mut)]")
    lines.append("#![allow(unused_imports)]")
    lines.append("#![allow(dead_code)]")
    lines.append("")

    for imp in snippet.imports:
        lines.append(imp)
    if snippet.imports:
        lines.append("")

    lines.append("#[test]")
    lines.append(f"fn test_synthesized_{test_index}() {{")

    for stmt in snippet.stmts:
        line = _render_stmt(stmt)
        if line:
            lines.append(f"    {line}")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def render_multi(
    snippets: list[SnippetIR],
    task_id: str,
    crate_name: Optional[str] = None,
) -> str:
    """Render multiple snippets as separate #[test] functions in one file."""
    cn = crate_name or (snippets[0].crate_name if snippets else "")
    lines: list[str] = []

    lines.append(f"//! Generated by rustsynth-pcpn for task: {task_id}")
    lines.append("//! This code is compilation-valid (not semantically verified).")
    lines.append("")
    lines.append("#![allow(unused_variables)]")
    lines.append("#![allow(unused_mut)]")
    lines.append("#![allow(unused_imports)]")
    lines.append("#![allow(dead_code)]")
    lines.append("")

    all_imports: set[str] = set()
    for s in snippets:
        all_imports.update(s.imports)
    for imp in sorted(all_imports):
        lines.append(imp)
    if all_imports:
        lines.append("")

    for i, snippet in enumerate(snippets):
        lines.append("#[test]")
        lines.append(f"fn test_synthesized_{i}() {{")
        for stmt in snippet.stmts:
            line = _render_stmt(stmt)
            if line:
                lines.append(f"    {line}")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def _render_stmt(stmt: Stmt) -> Optional[str]:
    if stmt.kind == StmtKind.LetBinding:
        mut = "mut " if stmt.is_mut else ""
        if stmt.var_type:
            return f"let {mut}{stmt.var_name}: {stmt.var_type} = {stmt.expr};"
        return f"let {mut}{stmt.var_name} = {stmt.expr};"

    if stmt.kind == StmtKind.Borrow:
        if stmt.var_type:
            return f"let {stmt.var_name}: {stmt.var_type} = {stmt.expr};"
        return f"let {stmt.var_name} = {stmt.expr};"

    if stmt.kind == StmtKind.Deref:
        if stmt.var_type:
            return f"let {stmt.var_name}: {stmt.var_type} = {stmt.expr};"
        return f"let {stmt.var_name} = {stmt.expr};"

    if stmt.kind == StmtKind.Clone:
        if stmt.var_type:
            return f"let {stmt.var_name}: {stmt.var_type} = {stmt.expr};"
        return f"let {stmt.var_name} = {stmt.expr};"

    if stmt.kind == StmtKind.FieldAccess:
        if stmt.var_type:
            return f"let {stmt.var_name}: {stmt.var_type} = {stmt.expr};"
        return f"let {stmt.var_name} = {stmt.expr};"

    if stmt.kind == StmtKind.FnCall:
        return stmt.expr

    if stmt.kind == StmtKind.Drop:
        return stmt.expr

    if stmt.kind == StmtKind.MethodCall:
        return f"{stmt.expr};"

    if stmt.kind == StmtKind.BlockOpen:
        return "{"

    if stmt.kind == StmtKind.BlockClose:
        return "}"

    if stmt.kind == StmtKind.Comment:
        return f"// {stmt.comment}"

    if stmt.kind == StmtKind.Hole:
        if stmt.hole:
            return f"/* {stmt.hole.id}: {stmt.hole.kind.value} */"
        return "/* HOLE */"

    return None
