"""
ExportScaffoldForLLM — Mode B: export scaffold.rs + holes.json.

Generates a Rust source file with HOLE placeholders and a companion
JSON file describing each hole's type, kind, and context.

Hole kinds:
  - literal:         needs a concrete literal value
  - constructor_arg: needs a constructor argument
  - trait_stub:      needs a trait implementation
  - assertion:       needs an assertion expression
"""

from __future__ import annotations

import json
from typing import Optional

from rustsynth.ir.snippet_ir import SnippetIR, Stmt, StmtKind, Hole, HoleKind


def export_scaffold(
    snippet: SnippetIR,
    task_id: str,
    crate_name: Optional[str] = None,
) -> tuple[str, str]:
    """Generate scaffold .rs source and holes .json.

    Returns (rust_source, holes_json_str).
    """
    cn = crate_name or snippet.crate_name
    lines: list[str] = []
    holes: list[dict] = []

    lines.append(f"//! Scaffold generated by rustsynth-pcpn for task: {task_id}")
    lines.append("//! Holes marked with /* HOLE_N */ require concretization.")
    lines.append("")
    lines.append("#![allow(unused_variables)]")
    lines.append("#![allow(unused_mut)]")
    lines.append("#![allow(unused_imports)]")
    lines.append("")

    for imp in snippet.imports:
        lines.append(imp)
    if snippet.imports:
        lines.append("")

    lines.append(f"fn test_scaffold_{task_id.replace('-', '_')}() {{")

    hole_counter = 0
    available_vars: list[str] = []

    for stmt in snippet.stmts:
        if stmt.kind == StmtKind.Hole and stmt.hole:
            hole = stmt.hole
            holes.append({
                "id": hole.id,
                "kind": hole.kind.value,
                "expected_type": hole.expected_type,
                "expected_trait": hole.expected_trait,
                "available_vars": list(available_vars),
            })
            lines.append(f"    /* {hole.id}: {hole.kind.value} — {hole.expected_type or hole.expected_trait or '?'} */")

        elif stmt.kind == StmtKind.LetBinding:
            expr = stmt.expr
            if expr == "Default::default()" or expr.startswith("todo!"):
                hole_id = f"HOLE_{hole_counter}"
                hole_counter += 1
                holes.append({
                    "id": hole_id,
                    "kind": HoleKind.Literal.value,
                    "expected_type": stmt.var_type,
                    "available_vars": list(available_vars),
                })
                expr = f"/* {hole_id}: literal {stmt.var_type or '?'} */"

            mut = "mut " if stmt.is_mut else ""
            if stmt.var_type:
                lines.append(f"    let {mut}{stmt.var_name}: {stmt.var_type} = {expr};")
            else:
                lines.append(f"    let {mut}{stmt.var_name} = {expr};")
            if stmt.var_name:
                available_vars.append(stmt.var_name)

        elif stmt.kind == StmtKind.Drop:
            lines.append(f"    {stmt.expr}")

        elif stmt.kind in (StmtKind.Borrow, StmtKind.Deref, StmtKind.Clone,
                           StmtKind.FieldAccess):
            if stmt.var_type:
                lines.append(f"    let {stmt.var_name}: {stmt.var_type} = {stmt.expr};")
            else:
                lines.append(f"    let {stmt.var_name} = {stmt.expr};")
            if stmt.var_name:
                available_vars.append(stmt.var_name)

        elif stmt.kind == StmtKind.FnCall:
            lines.append(f"    {stmt.expr}")

        elif stmt.kind == StmtKind.Comment:
            lines.append(f"    // {stmt.comment}")

    assertion_hole_id = f"HOLE_{hole_counter}"
    hole_counter += 1
    holes.append({
        "id": assertion_hole_id,
        "kind": HoleKind.Assertion.value,
        "available_vars": list(available_vars),
    })
    lines.append(f"    /* {assertion_hole_id}: assertion */")

    lines.append("}")
    lines.append("")

    rust_source = "\n".join(lines)
    holes_json = json.dumps({"task_id": task_id, "holes": holes}, indent=2)

    return rust_source, holes_json
