//! Generated by RustSynth PCPN Synthesizer
//!
//! This code demonstrates a valid Rust API call sequence.

#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]

fn main() {
    let counter_0 = Counter_new(); // Counter::new
}