//! Rust Code Emitter - 从 Firing 序列生成可编译的 Safe Rust 代码
//!
//! Translates witness firing sequences from the PCPN simulator into
//! compilable Safe Rust code. Supports single-trace and multi-trace modes.

use std::collections::{HashMap, HashSet};

use crate::pcpn::{Pcpn, TransitionKind};
use crate::simulator::TraceFiring;
use crate::types::{TyGround, TypeForm, VarId};

/// 从 transition 的 fn_path 中提取类型名和方法名
/// 例如 "Counter::get" -> Some(("Counter", "get"))
/// "make_pair" -> None
fn parse_method_path(fn_path: &str) -> Option<(&str, &str)> {
    // 处理泛型:先去掉 <...> 后缀
    let base = fn_path.split('<').next().unwrap_or(fn_path);
    if let Some(pos) = base.rfind("::") {
        let type_name = &base[..pos];
        let method_name = &base[pos + 2..];
        if !method_name.is_empty() {
            return Some((type_name, method_name));
        }
    }
    None
}

pub struct CodeEmitter<'a> {
    pcpn: &'a Pcpn,
    lines: Vec<String>,
    indent: usize,
    var_types: HashMap<VarId, TyGround>,
    var_names: HashMap<VarId, String>,
    var_is_ref: HashMap<VarId, bool>,
    var_is_mut_ref: HashMap<VarId, bool>,
    name_counter: usize,
}

impl<'a> CodeEmitter<'a> {
    pub fn new(pcpn: &'a Pcpn) -> Self {
        CodeEmitter {
            pcpn,
            lines: Vec::new(),
            indent: 1,
            var_types: HashMap::new(),
            var_names: HashMap::new(),
            var_is_ref: HashMap::new(),
            var_is_mut_ref: HashMap::new(),
            name_counter: 0,
        }
    }

    pub fn emit(&mut self, trace: &[TraceFiring]) -> String {
        self.reset();

        self.emit_header();
        self.push_line("fn main() {");

        for firing in trace {
            self.emit_firing(firing);
        }

        self.push_line("}");
        self.lines.join("\n")
    }

    /// Emit multiple traces as separate test functions in a single file
    pub fn emit_multi(&mut self, traces: &[Vec<TraceFiring>], crate_name: Option<&str>) -> String {
        self.lines.clear();

        self.push_line("//! Generated by RustSynth PCPN Synthesizer");
        self.push_line("//!");
        self.push_line(&format!(
            "//! {} test functions generated from {} witness traces.",
            traces.len(),
            traces.len()
        ));
        self.push_line("");
        self.push_line("#![allow(unused_variables)]");
        self.push_line("#![allow(unused_mut)]");
        self.push_line("#![allow(dead_code)]");
        self.push_line("");

        let use_types = self.collect_used_types(traces);
        if let Some(cn) = crate_name {
            if !use_types.is_empty() {
                self.push_line(&format!("use {}::{{{}}};", cn, use_types.join(", ")));
                self.push_line("");
            }
        }

        for (i, trace) in traces.iter().enumerate() {
            self.reset();
            self.push_line(&format!("fn test_{}() {{", i));

            for firing in trace {
                self.emit_firing(firing);
            }

            self.push_line("}");
            self.push_line("");
        }

        self.push_line("fn main() {");
        for i in 0..traces.len() {
            self.indent = 1;
            self.emit_line(&format!("test_{}();", i));
        }
        self.indent = 1;
        self.push_line("}");

        self.lines.join("\n")
    }

    fn reset(&mut self) {
        self.lines.clear();
        self.var_types.clear();
        self.var_names.clear();
        self.var_is_ref.clear();
        self.var_is_mut_ref.clear();
        self.name_counter = 0;
    }

    /// Collect non-primitive type names used across traces for `use` declarations
    fn collect_used_types(&self, traces: &[Vec<TraceFiring>]) -> Vec<String> {
        let mut types: HashSet<String> = HashSet::new();
        for trace in traces {
            for firing in trace {
                match &firing.kind {
                    TransitionKind::ConstProducer { ty, .. }
                    | TransitionKind::CreatePrimitive { ty }
                    | TransitionKind::CopyUse { ty } => {
                        if let TyGround::Path { name, .. } = ty {
                            types.insert(name.clone());
                        }
                    }
                    TransitionKind::ApiCall { fn_path, .. } => {
                        if let Some((type_name, _)) = parse_method_path(fn_path) {
                            let base = type_name.split('<').next().unwrap_or(type_name);
                            types.insert(base.to_string());
                        }
                    }
                    _ => {}
                }
            }
        }
        let mut sorted: Vec<String> = types.into_iter().collect();
        sorted.sort();
        sorted
    }

    fn emit_header(&mut self) {
        self.push_line("//! Generated by RustSynth PCPN Synthesizer");
        self.push_line("//!");
        self.push_line("//! This code demonstrates a valid Rust API call sequence.");
        self.push_line("");
        self.push_line("#![allow(unused_variables)]");
        self.push_line("#![allow(unused_mut)]");
        self.push_line("#![allow(dead_code)]");
        self.push_line("");
    }

    fn emit_firing(&mut self, firing: &TraceFiring) {
        match &firing.kind {
            TransitionKind::CreatePrimitive { ty } => {
                self.emit_create_primitive(firing, ty);
            }
            TransitionKind::ConstProducer { ty, fn_path } => {
                self.emit_const_producer(firing, ty, fn_path);
            }
            TransitionKind::ApiCall { fn_path, .. } => {
                self.emit_api_call(firing, fn_path);
            }
            TransitionKind::BorrowShrFirst { base_type } => {
                self.emit_borrow_shr_first(firing, base_type);
            }
            TransitionKind::BorrowShrNext { base_type } => {
                self.emit_borrow_shr_next(firing, base_type);
            }
            TransitionKind::BorrowMut { base_type } => {
                self.emit_borrow_mut(firing, base_type);
            }
            TransitionKind::EndBorrowShrKeepFrz { .. }
            | TransitionKind::EndBorrowShrUnfreeze { .. } => {
                self.emit_end_shr(firing);
            }
            TransitionKind::EndBorrowMut { .. } => {
                self.emit_end_mut(firing);
            }
            TransitionKind::Drop { .. } => {
                self.emit_drop(firing);
            }
            TransitionKind::CopyUse { ty } => {
                self.emit_copy_use(firing, ty);
            }
        }
    }

    fn emit_create_primitive(&mut self, firing: &TraceFiring, ty: &TyGround) {
        if let Some((_, token)) = firing.produced.first() {
            let var_name = self.fresh_var_name(&ty.short_name());
            self.var_names.insert(token.vid, var_name.clone());
            self.var_types.insert(token.vid, ty.clone());
            self.var_is_ref.insert(token.vid, false);

            let type_name = ty.short_name();
            let default_val = self.default_value(ty);
            self.emit_line(&format!(
                "let {}: {} = {}; // {}",
                var_name, type_name, default_val, firing.name
            ));
        }
    }

    fn emit_const_producer(&mut self, firing: &TraceFiring, ty: &TyGround, fn_path: &str) {
        if let Some((_, token)) = firing.produced.first() {
            let var_name = self.fresh_var_name(&ty.short_name());
            self.var_names.insert(token.vid, var_name.clone());
            self.var_types.insert(token.vid, ty.clone());
            self.var_is_ref.insert(token.vid, false);

            // 使用正确的 Rust 路径语法(如 Counter::new())
            let call = if let Some((type_name, fn_name)) = parse_method_path(fn_path) {
                format!("{}::{}()", type_name, fn_name)
            } else {
                format!("{}()", fn_path)
            };
            self.emit_line(&format!(
                "let mut {}: {} = {};",
                var_name,
                ty.short_name(),
                call
            ));
        }
    }

    fn emit_api_call(&mut self, firing: &TraceFiring, fn_path: &str) {
        let mut args: Vec<String> = Vec::new();
        let mut receiver: Option<(String, bool)> = None; // (var_name, is_ref)

        // 判断是否是方法调用,以及准备参数
        let method_info = parse_method_path(fn_path);
        let is_method_call = method_info.is_some() && !firing.consumed.is_empty();

        for (i, (_, token)) in firing.consumed.iter().enumerate() {
            let var_name = self.get_var_name(token.vid);
            if i == 0 && is_method_call {
                let is_ref = self.var_is_ref.get(&token.vid).copied().unwrap_or(false);
                receiver = Some((var_name, is_ref));
            } else {
                // 检查是否需要传递引用
                let is_param_ref = self.var_is_ref.get(&token.vid).copied().unwrap_or(false);
                if is_param_ref {
                    args.push(var_name);
                } else {
                    args.push(var_name);
                }
            }
        }

        let call_expr = if let (Some((recv, _)), Some((_, method_name))) = (&receiver, method_info)
        {
            format!("{}.{}({})", recv, method_name, args.join(", "))
        } else {
            // 自由函数或关联函数
            if let Some((type_name, fn_name)) = method_info {
                // 关联函数调用 Type::func(args)
                format!("{}::{}({})", type_name, fn_name, args.join(", "))
            } else {
                // 普通自由函数
                format!("{}({})", fn_path, args.join(", "))
            }
        };

        // 处理输出 token(过滤掉 Copy-return 的 token,它们的 vid 与 consumed 相同)
        let output_tokens: Vec<_> = firing
            .produced
            .iter()
            .filter(|(_, t)| !firing.consumed.iter().any(|(_, c)| c.vid == t.vid))
            .collect();

        if output_tokens.is_empty() {
            self.emit_line(&format!("{}; // {}", call_expr, firing.name));
        } else if output_tokens.len() == 1 {
            let (pid, token) = output_tokens[0];
            let place = &self.pcpn.places[*pid];
            let var_name = self.fresh_var_name(&place.base_type.short_name());
            self.var_names.insert(token.vid, var_name.clone());
            self.var_types.insert(token.vid, place.base_type.clone());

            let is_ref = matches!(place.form, TypeForm::RefShr | TypeForm::RefMut);
            let is_mut_ref = matches!(place.form, TypeForm::RefMut);
            self.var_is_ref.insert(token.vid, is_ref);
            self.var_is_mut_ref.insert(token.vid, is_mut_ref);

            // 引用不需要 mut,值类型可能需要 mut
            let type_annotation = match place.form {
                TypeForm::Value => format!(": {}", place.base_type.short_name()),
                TypeForm::RefShr => format!(": &{}", place.base_type.short_name()),
                TypeForm::RefMut => format!(": &mut {}", place.base_type.short_name()),
            };
            let let_kw = if is_ref { "let" } else { "let mut" };
            self.emit_line(&format!(
                "{} {}{} = {};",
                let_kw, var_name, type_annotation, call_expr
            ));
        } else {
            // 多返回值(罕见)
            self.emit_line(&format!("{}; // {}", call_expr, firing.name));
        }
    }

    fn emit_borrow_shr_first(&mut self, firing: &TraceFiring, base_type: &TyGround) {
        if firing.consumed.is_empty() || firing.produced.len() < 2 {
            return;
        }

        let owner_token = &firing.consumed[0].1;
        let ref_token = &firing.produced[1].1;

        let owner_var = self.get_var_name(owner_token.vid);
        let ref_var = self.fresh_var_name(&format!("ref_{}", base_type.short_name()));
        self.var_names.insert(ref_token.vid, ref_var.clone());
        self.var_types.insert(ref_token.vid, base_type.clone());
        self.var_is_ref.insert(ref_token.vid, true);

        self.emit_line(&format!(
            "let {} = &{}; // {}",
            ref_var, owner_var, firing.name
        ));
    }

    fn emit_borrow_shr_next(&mut self, firing: &TraceFiring, base_type: &TyGround) {
        if firing.produced.is_empty() {
            return;
        }

        let ref_token = &firing.produced[0].1;
        let ref_var = self.fresh_var_name(&format!("ref_{}", base_type.short_name()));
        self.var_names.insert(ref_token.vid, ref_var.clone());
        self.var_types.insert(ref_token.vid, base_type.clone());
        self.var_is_ref.insert(ref_token.vid, true);

        if let Some((_, frz_token)) = firing.consumed.first() {
            let owner_var = self.get_var_name(frz_token.vid);
            self.emit_line(&format!(
                "let {} = &{}; // {}",
                ref_var, owner_var, firing.name
            ));
        }
    }

    fn emit_borrow_mut(&mut self, firing: &TraceFiring, base_type: &TyGround) {
        if firing.consumed.is_empty() || firing.produced.len() < 2 {
            return;
        }

        let owner_token = &firing.consumed[0].1;
        let ref_token = &firing.produced[1].1;

        let owner_var = self.get_var_name(owner_token.vid);
        let ref_var = self.fresh_var_name(&format!("mut_{}", base_type.short_name()));
        self.var_names.insert(ref_token.vid, ref_var.clone());
        self.var_types.insert(ref_token.vid, base_type.clone());
        self.var_is_ref.insert(ref_token.vid, true);
        self.var_is_mut_ref.insert(ref_token.vid, true);

        self.emit_line(&format!(
            "let {} = &mut {}; // {}",
            ref_var, owner_var, firing.name
        ));
    }

    fn emit_end_shr(&mut self, firing: &TraceFiring) {
        for (_, token) in &firing.consumed {
            if self.var_is_ref.get(&token.vid).copied().unwrap_or(false) {
                let var_name = self.get_var_name(token.vid);
                self.emit_line(&format!("drop({}); // {}", var_name, firing.name));
                return;
            }
        }
    }

    fn emit_end_mut(&mut self, firing: &TraceFiring) {
        for (_, token) in &firing.consumed {
            if self
                .var_is_mut_ref
                .get(&token.vid)
                .copied()
                .unwrap_or(false)
            {
                let var_name = self.get_var_name(token.vid);
                self.emit_line(&format!("drop({}); // {}", var_name, firing.name));
                return;
            }
        }
    }

    fn emit_drop(&mut self, firing: &TraceFiring) {
        if let Some((_, token)) = firing.consumed.first() {
            let var_name = self.get_var_name(token.vid);
            self.emit_line(&format!("drop({}); // {}", var_name, firing.name));
        }
    }

    fn emit_copy_use(&mut self, firing: &TraceFiring, ty: &TyGround) {
        if firing.consumed.is_empty() || firing.produced.is_empty() {
            return;
        }

        let src_token = &firing.consumed[0].1;
        let dst_token = &firing.produced[0].1;

        let src_var = self.get_var_name(src_token.vid);
        let dst_var = self.fresh_var_name(&ty.short_name());
        self.var_names.insert(dst_token.vid, dst_var.clone());
        self.var_types.insert(dst_token.vid, ty.clone());
        self.var_is_ref.insert(dst_token.vid, false);

        self.emit_line(&format!(
            "let {} = {}; // {} (copy)",
            dst_var, src_var, firing.name
        ));
    }

    fn fresh_var_name(&mut self, hint: &str) -> String {
        let clean_hint = hint
            .chars()
            .filter(|c| c.is_alphanumeric() || *c == '_')
            .collect::<String>()
            .to_lowercase();
        let name = format!("{}_{}", clean_hint, self.name_counter);
        self.name_counter += 1;
        name
    }

    fn get_var_name(&self, vid: VarId) -> String {
        self.var_names
            .get(&vid)
            .cloned()
            .unwrap_or_else(|| format!("v{}", vid))
    }

    fn default_value(&self, ty: &TyGround) -> String {
        match ty {
            TyGround::Primitive(name) => match name.as_str() {
                "bool" => "false".to_string(),
                "char" => "'\\0'".to_string(),
                "i8" | "i16" | "i32" | "i64" | "i128" | "isize" => "0".to_string(),
                "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => "0".to_string(),
                "f32" | "f64" => "0.0".to_string(),
                _ => "Default::default()".to_string(),
            },
            TyGround::Unit => "()".to_string(),
            _ => "Default::default()".to_string(),
        }
    }

    fn emit_line(&mut self, line: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.lines.push(format!("{}{}", indent_str, line));
    }

    fn push_line(&mut self, line: &str) {
        self.lines.push(line.to_string());
    }
}

pub fn emit_rust_code(trace: &[TraceFiring], pcpn: &Pcpn) -> String {
    let mut emitter = CodeEmitter::new(pcpn);
    emitter.emit(trace)
}

/// Emit multiple witness traces as separate test functions
pub fn emit_multi_traces(
    traces: &[Vec<TraceFiring>],
    pcpn: &Pcpn,
    crate_name: Option<&str>,
) -> String {
    let mut emitter = CodeEmitter::new(pcpn);
    emitter.emit_multi(traces, crate_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_values() {
        let pcpn = Pcpn::new();
        let emitter = CodeEmitter::new(&pcpn);

        assert_eq!(emitter.default_value(&TyGround::primitive("i32")), "0");
        assert_eq!(emitter.default_value(&TyGround::primitive("bool")), "false");
        assert_eq!(
            emitter.default_value(&TyGround::path("Counter")),
            "Default::default()"
        );
    }

    use crate::apigraph::build_counter_api_graph;
    use crate::config::{GoalConfig, ParsedGoal};
    use crate::pcpn::Pcpn;
    use crate::simulator::{SimConfig, Simulator};

    #[test]
    fn test_emit_const_producer() {
        // 构造 Counter PCPN，模拟找到 "own Counter" 的 trace，然后生成代码
        let graph = build_counter_api_graph();
        let pcpn = Pcpn::from_api_graph(&graph);

        let goal = ParsedGoal::parse(&GoalConfig {
            want: "own Counter".to_string(),
            count: 1,
        }).unwrap();

        let config = SimConfig {
            max_steps: 20,
            stack_depth: 4,
            goal: Some(goal),
            ..Default::default()
        };

        let sim = Simulator::new(&pcpn, config);
        let result = sim.run();
        assert!(result.found);

        let code = emit_rust_code(&result.trace, &pcpn);
        assert!(code.contains("fn main()"), "Generated code should contain fn main()");
        assert!(code.contains("Counter::new()"), "Should call Counter::new()");
    }

    #[test]
    fn test_emit_into_value_sequence() {
        // 找到 Counter::new → Counter::into_value 的路径，生成代码
        let graph = build_counter_api_graph();
        let pcpn = Pcpn::from_api_graph(&graph);

        let goal = ParsedGoal::parse(&GoalConfig {
            want: "own i32".to_string(),
            count: 1,
        }).unwrap();

        let config = SimConfig {
            max_steps: 50,
            stack_depth: 4,
            goal: Some(goal),
            deny_transitions: vec!["const_i32".to_string(), "copy_use".to_string()],
            ..Default::default()
        };

        let sim = Simulator::new(&pcpn, config);
        let result = sim.run();
        assert!(result.found, "Should find path to own i32 via Counter");

        let code = emit_rust_code(&result.trace, &pcpn);
        assert!(code.contains("fn main()"));
        // 应包含 Counter::new 调用
        assert!(code.contains("Counter::new()"),
            "Code should contain Counter::new(), got:\n{}", code);
    }

    #[test]
    fn test_emit_borrow_and_method_call() {
        // 用 get(&self) 路径: Counter::new → borrow_shr → get → end → drop
        // 为此需要禁止 const_i32、copy_use、into_value
        let graph = build_counter_api_graph();
        let pcpn = Pcpn::from_api_graph(&graph);

        let goal = ParsedGoal::parse(&GoalConfig {
            want: "own i32".to_string(),
            count: 1,
        }).unwrap();

        let config = SimConfig {
            max_steps: 80,
            stack_depth: 4,
            goal: Some(goal),
            deny_transitions: vec![
                "const_i32".to_string(),
                "copy_use".to_string(),
                "into_value".to_string(),
            ],
            ..Default::default()
        };

        let sim = Simulator::new(&pcpn, config);
        let result = sim.run();
        assert!(result.found, "Should find path via borrow + get");

        let code = emit_rust_code(&result.trace, &pcpn);
        assert!(code.contains("fn main()"));
        // 应该包含 Counter::new 和某种借用
        assert!(code.contains("Counter::new()"),
            "Code should contain Counter::new(), got:\n{}", code);
        // 应该有 get 调用（可能是 .get() 方法调用或 Counter::get() 关联函数形式）
        assert!(code.contains("get("),
            "Code should contain get() call, got:\n{}", code);
    }

    #[test]
    fn test_emit_code_structure() {
        // 验证生成代码的结构完整性
        let graph = build_counter_api_graph();
        let pcpn = Pcpn::from_api_graph(&graph);

        let config = SimConfig {
            max_steps: 20,
            stack_depth: 4,
            goal: None,
            ..Default::default()
        };

        let sim = Simulator::new(&pcpn, config);
        let result = sim.run();
        assert!(result.found);

        let code = emit_rust_code(&result.trace, &pcpn);

        // 结构验证
        assert!(code.contains("#![allow(unused_variables)]"));
        assert!(code.contains("#![allow(unused_mut)]"));
        assert!(code.contains("fn main() {"));
        assert!(code.contains("}"));

        // 每一行 let 都应该有 =
        for line in code.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("let ") {
                assert!(trimmed.contains("="),
                    "let statement should have assignment: {}", trimmed);
            }
        }
    }
}
