//! Generated by RustSynth PCPN Synthesizer
//!
//! This code demonstrates a valid Rust API call sequence.

#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(dead_code)]

fn main() {
    let i32_0: i32 = 0; // const_i32
}